version: "3.7"

services:
  caddy:
    image: caddy:latest
    ports:
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/sites:/usr/share/caddy
      - $PWD/caddy_data:/data
      - $PWD/caddy_config:/config
